cadastro/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [

    path('admin/', admin.site.urls),
    path('funcionario/', include('funcionario.urls', namespace='funcionario')),
    path('', include('core.urls', namespace='core')),

]

core/urls.py
from django.urls import include, path



#a partir do Django 2 tem que criar o app_name
app_name = 'core'

#importa as views de core que está na mesma pasta
from . import views
urlpatterns = [
    path('', views.home, name='home'),
]

funcionario/urls.py
from django.contrib import admin
from django.urls import include, path



app_name = 'funcionario'

from . import views

urlpatterns = [

    path('',views.AddFuncionario,name='add_funcionario'),
    path('funcionario/lista',views.lista_funcionario,name='lista_funcionario'),

]

core/models.py
from django.db import models

# Create your models here.

funcionario/models.py
from django.db import models
from django.contrib.auth.models import User

class Funcionario(models.Model):
    nome = models.CharField(max_length=100,help_text='Nome',blank=False)
    cpf = models.CharField(max_length=14,help_text='CPF',blank=False,default='')
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='perfil',default='',blank=False)
    email = models.CharField(max_length=100,help_text='e-mail',default='',blank=False)
    celular = models.CharField(max_length=11,help_text='celular',default='',blank=False)
    rg = models.CharField(max_length=15, help_text='rg', default='',blank=False)
    endereco = models.CharField(max_length=100, help_text='endereco', default='',blank=False)
    salario = models.CharField(max_length=10, help_text='salario', default='',blank=False)

class Meta:
    ordering=['-id']


def __str__(self):
    return self.nome

funcionario/forms.py
from django import forms
from funcionario.models import Funcionario


class FuncionarioForm(forms.ModelForm):
    class Meta:
        model = Funcionario
        # fields = ['nome','cpf','email','celular','rg','endereco','salario','user',]
        fields = '__all__'

core/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'base.html',{})

funcionario/views.py
from django.shortcuts import render,redirect, get_list_or_404,get_object_or_404
from funcionario.models  import Funcionario
from django.contrib import messages
from funcionario.forms import FuncionarioForm

def AddFuncionario(request):
    template_name = 'funcionario/add_funcionario.html'
    context = {}
    if request.method == 'POST':
        form = FuncionarioForm(request.POST)
        if form.is_valid():
            # f = form.save(commit=False)
            form.save()
            messages.success(request, "Usuário salvo com sucesso!")
        else:
            messages.error(request, "Erro ao salvar dados!")
    form = FuncionarioForm()
    context['form'] = form
    return render(request,template_name,context)



def lista_funcionario(request):
    template_name = 'funcionario/lista_funcionario.html'
    funcionario = Funcionario.objects.all().reverse()
    context = {
       'funcionario':funcionario
    }
    return render(request,template_name,context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0" />
  <title>
    {% block title %} Empresa
    {% endblock title%}

  </title>


  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'css/materialize.css' %} " type="text/css" rel="stylesheet" media="screen,projection" />


</head>

<body>


  <nav class="orange darken-4" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo">Empresa</a>
      <ul class="right hide-on-med-and-down">
        {% comment %} {% if user.is_authenticated%} {% endcomment %}
        <li><a href="/">Inicio</a></li>
        <!-- Dropdown Trigger -->
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown">Funcionarios<i
              class="material-icons right">arrow_drop_down</i></a></li>
        <li><a href="">Sair</a></li>
      </ul>


      <ul id="dropdown" class="dropdown-content">
        <li><a href="{% url 'funcionario:add_funcionario'  %}">Novo</a></li>
        <li><a href="{% url 'funcionario:lista_funcionario'  %}">Listar</a></li>
      </ul>


      </ul>

      <ul id="nav-mobile" class="sidenav">
        {% comment %} {% if user.is_authenticated%} {% endcomment %}
        <li><a href="">Inicio</a></li>
        <li><a href="">Perfil</a></li>
        <li><a href="">Sair</a></li>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Dropdown<i
              class="material-icons right">arrow_drop_down</i></a></li>



        {% comment %} {% else%} {% endcomment %}

        <li><a href="">Criar Conta</a></li>
        <li><a href="">Login</a></li>

        {% comment %} {%endif%} {% endcomment %}
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  </div>

  {% block body%}


  {% endblock body %}





  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'js/materialize.js' %}"></script>
  <script src="{% static 'js/init.js' %}"></script>
  <script>
    $(document).ready(function () {
      $('select').formSelect();
    });

    let dateObj = new Date();
    //DATEPICKER
    $(document).ready(function () {
      $('.datepicker').datepicker({
        yearRange: [1930, dateObj.getFullYear()],
        format: 'dd/mm/yyyy'
      });
    });
    //NAVBAR DROPDOWN


     //DROPDOWN FUNCIONARIO
    $(".dropdown-trigger").dropdown({
      inDuration: 300,
      outDuration: 225,
      constrain_width: false, // Does not change width of dropdown to that of the activator
      hover: false, // Activate on hover
      gutter: 0, // Spacing from edge
      belowOrigin: true, // Displays dropdown below the button
      alignment: 'left' //

    });
     //DROPDOWN PROFESSOR
    $(".dropdown-trigger2").dropdown({
      inDuration: 300,
      outDuration: 225,
      constrain_width: false, // Does not change width of dropdown to that of the activator
      hover: false, // Activate on hover
      gutter: 0, // Spacing from edge
      belowOrigin: true, // Displays dropdown below the button
      alignment: 'center' //

    });

    /* MODAL*/
    $(document).ready(function () {
      $('.modal').modal();
    });




  </script>

</body>

</html>

templates/funcionario/add_funcionario.html
{% extends 'base.html' %}

{%load widget_tweaks%}

{% block title %}
{{block.super}} - Cadastro de Funcionarios
{% endblock title %}

{% block body %}




<div class="container">
    {% include 'partials/messages.html' %}

    <div class="row">
        <div class="input-field col s5">

            <div class="form-group">
                <h4>Novo Funcionario</h4>
            </div>
            <form action="." method="POST" autocomplete="off">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.name.id_for_label }}">Nome:</label>
                    {{ form.nome|add_class:"form-control"|attr:"autofocus" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.user.id_for_label }}">Usuário:</label>
                    {{ form.user|add_class:"form-control"|attr:"autofocus" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.cpf.id_for_label }}">CPF:</label>
                    {{ form.cpf|add_class:"form-control" |attr:"autofocus"}}
                </div>
                <div class="form-group">
                    <label for="{{ form.email.id_for_label }}">E-Mail:</label>
                    {{ form.email|add_class:"form-control" |attr:"autofocus"}}
                </div>

                <div class="form-group">
                    <label for="form.celular.id_for_label">Celular:</label>
                    {{form.celular|add_class:"form-control" |attr:"autofocus"}}
                </div>

                <div class="form-group">
                    <label for="form.rg.id_for_label">RG:</label>
                    {{form.rg|add_class:"form-control" |attr:"autofocus"}}

                </div>

                <div class="form-group">
                    <label for="form.endereco.id_for_label">Endereço:</label>
                    {{form.endereco|add_class:"form-control" |attr:"autofocus"}}

                </div>

                <div class="form-group">
                    <label for="form.salario.id_for_label">Salario:</label>
                    {{form.salario|add_class:"form-control" |attr:"autofocus"}}

                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    <button type="reset" class="btn btn-primary">Limpar</button>
                </div>

        </div>



        </form>
    </div>
</div>




</div>

{% endblock body%}

templates/funcionario/lista_funcionario.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

Lista de Funcionarios - {{ block.super }}

{% endblock title %}


{% block body %}
<div class="container">
    <h2>Lista de Funcionarios</h2>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Id</th>
                        <th scope="col">Nome</th>
                        <th scope="col">CPF</th>
                        <th scope="col">Celular</th>
                        <th scope="col">E-mail</th>
                        <th scope="col">Salario</th>
                        <th scope="col">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for funcionario in funcionario %}
                    <tr>
                        <th scope="row">#</th>
                        <td>{{ funcionario.id }}</td>
                        <td>{{ funcionario.nome }}</td>
                        <td>{{ funcionario.cpf }}</td>
                        <td>{{ funcionario.celular }}</td>
                        <td>{{ funcionario.email}}</td>
                        <td>{{ funcionario.salario}}</td>
                        <td>Editar - Excluir</td>


                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>


</div>



{% endblock body %}

templates/partials/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} sucesso" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <i class="material-icons">check</i>
            </button>
        </div>

        <style>
        	.sucesso {
        		color:darkgreen;
        		background-color: lightgreen;
        		padding:10px;
        		text-align:center;
        		border-radius: 25px;
        		margin-top:15px;
        	}
        	.check {
        		font-size:5px !important;
        	}
        </style>
    {% endfor %}
{% endif %}